on:
  push:
    branches:
      - develop  # Aciona a ação ao enviar mudanças para a branch "develop"

jobs:
  build:
    runs-on: ubuntu-latest

    env:

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'  # Versão do Java usada no projeto
          distribution: temurin

      - name: Setup Maven
        run: mvn -version  # Verifica a versão do Maven


      - name: Run Tests
        run: mvn test

      - name: Build with Maven
        run: mvn clean package  # Compila o projeto