name: Build, Test, and Validate with PostgreSQL

on:
  push:
    branches:
      - main  # Aciona a ação ao enviar mudanças para a branch "develop"

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15  # Versão do PostgreSQL
        ports:
          - 5432:5432  # Porta padrão do PostgreSQL
        env:
          POSTGRES_USER: engstrategy  # Usuário do banco
          POSTGRES_PASSWORD: engstrategy1234@  # Senha do banco
          POSTGRES_DB: db_mundo_animal  # Banco de dados usado nos testes

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'  # Versão do Java usada no projeto
          distribution: temurin

      - name: Setup Maven
        run: mvn -version  # Verifica a versão do Maven

      - name: Configure persistence.xml for tests
        run: |
          sed -i 's|<property name="jakarta.persistence.jdbc.url" value=".*"/>|<property name="jakarta.persistence.jdbc.url" value="jdbc:postgresql://localhost:5432/db_mundo_animal"/>|' src/main/resources/META-INF/persistence.xml
          sed -i 's|<property name="jakarta.persistence.jdbc.user" value=".*"/>|<property name="jakarta.persistence.jdbc.user" value="engstrategy"/>|' src/main/resources/META-INF/persistence.xml
          sed -i 's|<property name="jakarta.persistence.jdbc.password" value=".*"/>|<property name="jakarta.persistence.jdbc.password" value="engstrategy1234@"/>|' src/main/resources/META-INF/persistence.xml

      - name: Wait for PostgreSQL
        run: |
          for i in {1..15}; do
            if pg_isready -h localhost -p 5432 -U engstrategy; then
              echo "PostgreSQL is ready!"
              exit 0
            fi
            echo "Waiting for PostgreSQL..."
            sleep 2
          done
          echo "PostgreSQL failed to start"
          exit 1

      - name: Show PostgreSQL Logs
        run: docker logs $(docker ps -q --filter "name=postgres")

      - name: Run Tests
        run: mvn test

      - name: Build with Maven
        run: mvn clean package  # Compila o projeto